name: Add Reviewers and Assignee to PR

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  add_reviewers_and_assignee:
    runs-on: ubuntu-latest

    steps:
      - name: Add Reviewers
        run: |
          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.DECKBLUE_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers \
            -d '{"reviewers": ["gildaswise", "myConsciousness"]}'
      - name: Set Assignee to PR Creator
        run: |
          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.DECKBLUE_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/assignees \
            -d '{"assignees": ["${{ github.actor }}"]}'
