name: Add Reviewers to PR

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  add_reviewers:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Add Reviewers
        run: |
          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.DECKBLUE_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers \
            -d '{"reviewers": ["gildaswise", "myConsciousness"]}'
