name: Validate Arb Format

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.arb"
  push:
    branches:
      - main
    paths:
      - "**.arb"

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@v1.3

      - name: Validate Format
        run: dart run ./bin/validate_arb_format.dart
